function G_torq = G_fun(q1,q2,q3,q4,q5,q6)
%G_FUN
%    G_TORQ = G_FUN(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    01-Oct-2022 21:26:53

t2 = q2+q3+q4;
t3 = -q5;
t9 = atan(3.818188629788691e-2);
t10 = 9.934139466657452e+7;
t4 = q5+t2;
t5 = sin(t2);
t7 = t2+t3;
t11 = q2+q3+t9;
t6 = sin(t4);
t8 = sin(t7);
t12 = cos(t11);
t13 = t5.*1.5980750946;
t14 = t10.*t12.*2.4525e-7;
t16 = t6.*1.680635215845e-1;
t18 = t8.*1.680635215845e-1;
t15 = -t14;
t17 = -t16;
G_torq = [0.0,t13+t15+t17+t18-cos(q2).*4.387468545e+1,t13+t15+t17+t18,t13+t17+t18,t17-t18,0.0];
