function g_st_mat = g_st_fun(q1,q2,q3,q4,q5,q6)
%G_ST_FUN
%    G_ST_MAT = G_ST_FUN(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    01-Oct-2022 21:26:53

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = sin(q5);
t13 = sin(q6);
t14 = q2+q3;
t15 = cos(t14);
t16 = q4+t14;
t17 = sin(t14);
t19 = t2.*t12;
t21 = t8.*t12;
t18 = cos(t16);
t20 = sin(t16);
t22 = t2.*t6.*t18;
t23 = t6.*t8.*t18;
t24 = -t23;
t25 = t21+t22;
t26 = t19+t24;
mt1 = [t7.*t25-t2.*t13.*t20,-t7.*t26-t8.*t13.*t20,t13.*t18+t6.*t7.*t20,0.0,-t13.*t25-t2.*t7.*t20,t13.*t26-t7.*t8.*t20,t7.*t18-t6.*t13.*t20,0.0,t6.*t8-t18.*t19,-t2.*t6-t18.*t21,-t12.*t20,0.0,t8.*(6.7e+1./5.0e+2)-t2.*t3.*(1.7e+1./4.0e+1)+t6.*t8.*7.71e-2-t18.*t19.*7.71e-2-t2.*t3.*t4.*3.9225e-1+t2.*t9.*t10.*3.9225e-1+(t2.*t5.*t17)./1.0e+1+(t2.*t11.*t15)./1.0e+1];
mt2 = [t2.*(-6.7e+1./5.0e+2)-t2.*t6.*7.71e-2-t3.*t8.*(1.7e+1./4.0e+1)-t18.*t21.*7.71e-2-t3.*t4.*t8.*3.9225e-1+t8.*t9.*t10.*3.9225e-1+(t5.*t8.*t17)./1.0e+1+(t8.*t11.*t15)./1.0e+1,t9.*(-1.7e+1./4.0e+1)-t17.*3.9225e-1-(t5.*t15)./1.0e+1+(t11.*t17)./1.0e+1-t12.*(t5.*t17.*7.71e-2+t11.*t15.*7.71e-2)+1.63e+2./1.0e+3,1.0];
g_st_mat = reshape([mt1,mt2],4,4);
